#!/bin/bash

source $PROJECT_PATH/.env

BEFORE_SCRIPT=$PROJECT_PATH/custom-scripts/media-before
AFTER_SCRIPT=$PROJECT_PATH/custom-scripts/media-after

if [ -f "$BEFORE_SCRIPT" ]; then
    source $BEFORE_SCRIPT
fi

source $PROJECT_PATH/.config/scripts/parts/media-import.bash

if [ -f "$AFTER_SCRIPT" ]; then
    source $AFTER_SCRIPT
fi
