#!/bin/bash

PROJECTPATH="/project"
if [[ -f "/vagrant/.config/config-wrapper.sh" ]]; then
  PROJECTPATH="/vagrant"
fi
. $PROJECTPATH/.config/config-wrapper.sh

if wp plugin is-installed --path=$WEBROOT loco-translate
then
    wp plugin activate --path=$WEBROOT loco-translate
fi

if wp plugin is-installed --path=$WEBROOT pattern-manager
then
    wp plugin activate --path=$WEBROOT pattern-manager
fi