#!/bin/bash

PROJECTPATH="/project"
if [[ -f "/vagrant/.config/config-wrapper.sh" ]]; then
  PROJECTPATH="/vagrant"
fi
. $PROJECTPATH/.config/config-wrapper.sh

for PLUGIN in "${LOCAL_PLUGINS[@]}" ; do
  if wp plugin is-installed --path="$WEBROOT" "$PLUGIN"
  then
      wp plugin activate --path="$WEBROOT" "$PLUGIN"
  fi
done