kind: pipeline
name: default

steps:
  - name: deploy
    image: jcodigi/zipdeploy
    pull: true
    settings:
      exclude: /.drone*
      user: webmaster
      host: pilvi.jco.fi
      target: /var/www/files/jco
    environment:
      SSH_KEY:
        from_secret: ssh_key
