#!/bin/bash

PROJECTPATH="/project"

. $PROJECTPATH/.config/config-wrapper.sh

for PLUGIN in "${LOCAL_PLUGINS[@]}" ; do
  if wp plugin is-installed --path="$WEBROOT" "$PLUGIN"
  then
      wp plugin activate --path="$WEBROOT" "$PLUGIN"
  else
    wp plugin install --path=$WEBROOT --activate "$PLUGIN"
  fi
done
