GITIGNORE="$WEBROOT/wp-content/plugins/.gitignore"

echo "### Autogenerated by jcore-cli, will be overwritten" > ${GITIGNORE}
for PLUGIN in ${PLUGIN_GIT} ; do
  echo "Including /wp-content/plugins/${PLUGIN} in git"
  echo \!/${PLUGIN}/ >> "${GITIGNORE}"
  echo \!/${PLUGIN}/** >> "${GITIGNORE}"
done
