[jcore3]
branch = "hurricane"
branches = ["gintonic", "hurricane"]
themeUrl = "https://github.com/JCO-Digital/jcore-ilme/archive/refs/heads/{{branch}}.zip"

[jcore2]
branch = "grasshopper"
branches = ["elduelo", "fluffycritter", "grasshopper"]
themeUrl = "https://files.jco.fi/jcore2-child-{{branch}}.zip"
child = true

[[jcore2.submodules]]
path = "wp-content/themes/jcore2"
repo = "git@bitbucket.org:jcodigital/jcore2.git"
useBranch = true

[blank]
branch = ""
branches = []

[jcore1]
branch = "master"
branches = ["master"]
child = true

[[jcore1.submodules]]
path = "wp-content/themes/jcore"
repo = "git@bitbucket.org:jcodigital/jcore.git"
useBranch = true
