name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: git archive --format=zip --output=main.zip main
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "main.zip"
