name: Release

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: git archive --format=zip --output=release.zip $GITHUB_REF * .config .gitignore .gitattributes
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
